# dependencies:
#   - uniswap/contracts@1.0.1
# compiler:
#   solc:
#     remappings:
#       - '@uniswap=Uniswap/v2-core@1.0.1'

networks:
  default: alchemy-arbitrum
  alchemy-arbitrum:
    markets:
      sushi_v2: 
        factory: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
        solidly: false
        fee_type: 0
        max_fee: 0.003
        router: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
      camelot: 
        factory: "0x6EcCab422D763aC031210895C81787E87B43A652"
        solidly: true
        stableSwap: true
        fee_type: 1
        router: "0xc873fEcbd354f5A56E00E710B90EF4201db2448d"
      arbitrum_exchange: 
        factory: "0x1C6E968f2E6c9DEC61DB874E28589fd5CE3E1f2c"
        solidly: false
        fee_type: 2
        router: "0x7238FB45146BD8FcB2c463Dc119A53494be57Aac"
      ramses_exchange: 
        factory: "0xAAA20D08e59F6561f242b08513D36266C5A29415"
        solidly: true
        stableSwap: false
        fee_type: 3
        router: "0xAAA87963EFeB6f7E0a2711F397663105Acb1805e"
      zyber_swap: 
        factory: "0xaC2ee06A14c52570Ef3B9812Ed240BCe359772e7"
        solidly: false
        fee_type: 2
        router: "0x16e71B13fE6079B4312063F7E81F76d165Ad32Ad"
      trader_joe_v1: 
        factory: "0xaE4EC9901c3076D0DdBe76A520F9E90a6227aCB7"
        solidly: false
        fee_type: 0
        max_fee: 0.003
        router: "0xbeE5c10Cf6E4F68f831E11C1D9E59B43560B3642"
      meerkat_finance: 
        factory: "0xfe3699303D3Eb460638e8aDA2bf1cFf092C33F22"
        solidly: false
        fee_type: 2
        router: "0x4F879a9d95e01041dDAA607A65F04e0EDbD04139"
      solid_lizard: 
        factory: "0x734d84631f00dC0d3FCD18b04b6cf42BFd407074"
        solidly: true
        stableSwap: false
        fee_type: 4
        router:  "0xF26515D5482e2C2FD237149bF6A653dA4794b3D0"
      3xcalibur: 
        factory: "0xD158bd9E8b6efd3ca76830B66715Aa2b7Bad2218"
        solidly: true
        stableSwap: false
        fee_type: 5
        router: ""
      sterling_finance: 
        factory: "0xF7A23B9A9dCB8d0aff67012565C5844C20C11AFC"
        solidly: true
        stableSwap: false
        fee_type: 6
        router: "0x0cBD3aEa90538a1Cf3C60B05582b691f6d2b2B01"
      alien_fi: 
        factory: "0xac9d019B7c8B7a4bbAC64b2Dbf6791ED672ba98B"
        solidly: false
        fee_type: 0
        max_fee: 0.0025
        router: ""
      oreo_swap: 
        factory: "0x20fAfD2B0Ba599416D75Eb54f48cda9812964f46"
        solidly: false
        fee_type: 0
        max_fee: 0.0025
        router: "0x38eEd6a71A4ddA9d7f776946e3cfa4ec43781AE6"
      arb_swap: 
        factory: "0xd394E9CC20f43d2651293756F8D320668E850F1b"
        solidly: false
        fee_type: 0
        max_fee: 0.003
        router: "0xD01319f4b65b79124549dE409D36F25e04B3e551"
      chronos:
        factory: "0xCe9240869391928253Ed9cc9Bcb8cb98CB5B0722"
        solidly: true
        stableSwap: false
        fee_type: 7
        router: ""
      auragi:
        factory: "0xa36b55DBe8e83Eb69C686368cF93ABC8A238CC5f"
        solidly: true
        stableswap: false
        fee_type: 2
        router: "0x0FaE1e44655ab06825966a8fCE87b9e988AB6170"
      mindgames:
        factory: "0x7C7F1c8E2b38d4C06218565BC4C9D8231b0628c0"
        solidly: false
        fee_type: 0
        max_fee: 0.003
        router: "0x750eD5cF0f5278be9C6562399f0791dD221C4f83"
      magicswap:
        factory: "0x015e379Ce0Ff195228b3A9eBDFA13F9afC155Dd7"
        solidly: false
        fee_type: 0
        max_fee: 0.003
        router: "0x23805449f91bB2d2054D9Ba288FdC8f09B5eAc79"
      swapr:
        factory: "0x359F20Ad0F42D75a5077e65F30274cABe6f4F01a"
        solidly: false
        fee_type: 2
        router: "0x530476d5583724A89c8841eB6Da76E7Af4C0F17E"
      swapfish:
        factory: "0x71539D09D3890195dDa87A6198B98B75211b72F3"
        solidly: false
        fee_type: 2
        router: "0xcDAeC65495Fa5c0545c5a405224214e3594f30d8"
      # Dex swap requires the call comes from an allow list of contracts -- most likely want to keep it all internal
      # dex_swap
      #   factory: "0x3E40739d8478c58f9B973266974C58998D4F9e8b"
      #   solidly: False
      #   fee_type: 2

      # usd_contracts:
      #   usdc:
      #     address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      #     decimals: 6
      #   usdt:
      #     address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      #     decimals: 6
      #   busd:
      #     address: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
      #     decimals: 18
      #   dai:
      #     address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
      #     decimals: 18
      #   frax:
      #     address: "0x853d955aCEf822Db058eb8505911ED77F175b99e"
      #     decimals: 18
      #   tusd:
      #     address: "0x0000000000085d4780B73119b644AE5ecd22b376"
      #     decimals: 18
      #   usdp:
      #     address: "0x8E870D67F660D95d5be530380D0eC0bd388289E1"
      #     decimals: 18
      #   usdd:
      #     address: "0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6"
      #     decimals: 18
      #   gusd:
      #     address: "0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd"
      #     decimals: 2
      #   cusdc:
      #     address: "0x39AA39c021dfbaE8faC545936693aC917d5E7563"
      #     decimals: 8
      #   cdai:
      #     address: "0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643"
      #     decimals: 8
      #   mim:
      #     address: "0x99D8a9C45b2ecA8864373A26D1459e3Dff1e17F3"
      #     decimals: 18
      #   dola:
      #     address: "0x865377367054516e17014CcdED1e7d814EDC9ce4"
      #     decimals: 18
      #   ousd:
      #     address: "0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86"
      #     decimals: 18
      #   wcusd:
      #     address: "0xad3E3Fc59dff318BecEaAb7D00EB4F68b1EcF195"
      #     decimals: 18
      #   fei:
      #     address: "0x956F47F50A910163D8BF957Cf5846D573E7f87CA"
      #     decimals: 18
      #   usdk:
      #     address: "0x1c48f86ae57291F7686349F12601910BD8D470bb"
      #     decimals: 18  
      # verify: False
  development:
    verify: False
dotenv: .env
wallets:
  from_key: ${TESTNET_PRIVATE_KEY}